#!/usr/bin/env php
<?php
/*
 * This file is part of DBUnit.
 *
 * (c) Sebastian Bergmann <sebastian@phpunit.de>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

foreach (array(__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php') as $file) {
    if (file_exists($file)) {
        define('DBUNIT_COMPOSER_INSTALL', $file);
        break;
    }
}

unset($file);

if (!defined('DBUNIT_COMPOSER_INSTALL')) {
    fwrite(STDERR,
        'You need to set up the project dependencies using the following commands:' . PHP_EOL .
        'wget http://getcomposer.org/composer.phar' . PHP_EOL .
        'php composer.phar install' . PHP_EOL
    );
    die(1);
}

require DBUNIT_COMPOSER_INSTALL;

$command = new PHPUnit_Extensions_Database_UI_Command(
    new PHPUnit_Extensions_Database_UI_ModeFactory
);

$command->main(
    new PHPUnit_Extensions_Database_UI_Mediums_Text($_SERVER['argv']),
    new PHPUnit_Extensions_Database_UI_Context
);
